module.exports =  {
  GET_NODES: 'get-nodes',
  ADD_NODE: 'add-node',
  DELETE_NODE: 'delete-node',
  IMPORT_NODES: 'import-nodes',
  EXPORT_NODES: 'export-nodes',
  GET_CHAINS: 'get-chains',
  GET_BLOCKS: 'get-blocks',
  GET_BLOCK: 'get-block',
  SEARCH: 'search',
  GET_TRANSACTION: 'get-transaction',
  GET_COMMITTEES: 'get-committees',
  GET_PENDING_TRANSACTIONS: 'get-pending-transactions',
  GET_TOKENS: 'get-tokens',
  CALL_RPC: 'call-rpc',
};
