export const GET_PENDING_TRANSACTIONS = 'GET_PENDING_TRANSACTIONS';
export const GET_PENDING_TRANSACTIONS_SUCCESS = 'GET_PENDING_TRANSACTIONS_SUCCESS';
export const GET_PENDING_TRANSACTIONS_FAILED = 'GET_PENDING_TRANSACTIONS_FAILED';
